RestClients:
  #The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
  DocuSign eSignature (DocuSign REST API):
    UUID: 17e5dc27-5699-4717-ae6c-e2c8f1e2a30f
    Url: http://{ivy.engine.host}:{ivy.engine.http.port}/{ivy.request.application}/api/docuSignMock
    Icon: res:/webContent/icons/docusign.png
    Features:
    - ch.ivyteam.ivy.rest.client.mapper.JsonFeature
    - net.docusign.auth.OAuth2Feature
    - ch.ivyteam.ivy.rest.client.security.CsrfHeaderFeature
    Properties:
      AUTH.integrationKey: test-key
      AUTH.secretKey: ${decrypt:\u00E8\u00BD\u0080\u007C\u0051\u0095\u00D1\u0071\u0070\u0047\u0072\u00B5\u00BC\u00E0\u004B\u00A9\u00BD\u00A4\u0072\u0070\u004A\u00F0\u0043\u0030\u0032\u00D2\u00AA\u0035\u0027\u001C\u0009\u009A\u0082\u0005\u0028\u00EA\u0012\u00B1\u0076\u0052\u006B\u00EA\u005F\u00CE\u00A1\u00E0\u00CA\u004D\u0047\u0065\u0043\u004F\u00F4\u00DE\u0091\u003C\u0035\u0018\u005F\u00F2\u0066\u0026\u00F7\u0002\u00CE\u000E\u00B9\u00FF\u000B\u00FD\u00C3\u00AA\u000E\u0056\u004B\u00F8\u00AE\u00C9\u00E1\u0068}
      AUTH.baseUri: http://{ivy.engine.host}:{ivy.engine.http.port}/{ivy.request.application}/api/docuSignMock/oauth
      AUTH.systemUserId: test-user
      AUTH.systemKeyFile: testKey.pem
      PATH.accountId: placeholder
