pipeline {
  agent {
    dockerfile {
      dir 'market/connector'
    }
  }

  options {
    buildDiscarder(logRotator(numToKeepStr: '60', artifactNumToKeepStr: '10'))
  }

  triggers {
    cron '@midnight'
  }

  parameters {
    string(name: 'engineListUrl',
      description: 'Engine to use for build',
      defaultValue: 'https://jenkins.ivyteam.io/job/ivy-core_product/job/master/lastSuccessfulBuild/')
  }

  stages {
    stage('build') {
      steps {
          dir('market/connector'){
              script {
                def mavenParameters = "-Divy.engine.list.url=${params.engineListUrl} " +
                  "-Divy.engine.version=[9.2.0,] -Dmaven.test.failure.ignore=true "
                maven cmd: "clean verify " + mavenParameters
              }
          }
      }
      post {
        always {
          recordIssues tools: [mavenConsole()], unstableTotalAll: 1, filters: [
            excludeMessage('.*-illegal-access=warn.*'), // java11
            excludeMessage('.*Filtering of parent/child POMs.*'), // maven invoker
          ]
          junit '**/target/*-reports/**/*.xml'
        }
      }
    }
  }
}
